### ISSUE TITLE
about new version tips window

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#12]
**The fixed prompt box experience of the new version of OCC 1.11.0 is not very good. The prompt box should still follow the mouse movement. The right user closes at any time instead of a separate window. This is often blocked by the main window, which is very uncomfortable!**

**Comment by btwise** [comment]
**Bugs found in 1.11.0:**
In the UEFI-> Protocol section, AppleSmcIo and OSInfo options do not work properly. When selecting AppleSmcio, HashService will be selected together. When selecting HashService, AppleSmcio will also be selected together. When selecting Osinfo, UnicodeCollation will also be selected at the same time. , And vice versa, these options cannot be selected individually!
And AppleSmcIo is set to true in the config.plist file, but it is not selected in the OCC display.

**Comment by mackie100** [comment]
> The fixed prompt box experience of the new version of OCC 1.11.0 is not very good. The prompt box should still follow the mouse movement. The right user closes at any time instead of a separate window. This is often blocked by the main window, which is very uncomfortable!

This is the right solution for now............

> **Bugs found in 1.11.0:**
> In the UEFI-> Protocol section, AppleSmcIo and OSInfo options do not work properly. When selecting AppleSmcio, HashService will be selected together. When selecting HashService, AppleSmcio will also be selected together. When selecting Osinfo, UnicodeCollation will also be selected at the same time. , And vice versa, these options cannot be selected individually!
> And AppleSmcIo is set to true in the config.plist file, but it is not selected in the OCC display.

Thanks for your repo.... Going to be fixed....... 👍

**Comment by btwise** [comment]
OC has added an 'AllowSetDefault' option, please add it in time!
