### ISSUE TITLE
About the problems in the PlatformInfo part of OpenCore Configurator (more serious)

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#17]
### About the problems in the PlatformInfo part of OpenCore Configurator (more serious)
 **1.Using the PlatformInfo part of the OpenCore bootloader**
         If Automatic = Yes, OC will not apply all the contents of DataHub, PlatformNVRAM, and SMBIOS. Automatic requirements must cooperate with the Generic part. The details of OpenCore.efi will complete all automatic filling according to the SystemProductName match in Generic.So it is recommended: if "Automatic = Yes", "DataHub," PlatformNVRAM "," SMBIOS "The "Add this section" option should be unchecked automatically, and the font prompt of this option should be designed to be larger and more eye-catching, and the content of the prompt Can be set to "Add this content in config.plist"
  2.After multiple verifications and tests, all the values of PlatformInfo are filled and the copy is compared with SimpleFull.plist in OpenCore Release. It is found that if the SMBIOS data selection model is automatically filled or imported, the data types of FirmwareFeaturesMask and FirmwareFeatures in PlatformNVRAM and SMBIOS will Become a String type, which should actually be a DATA type, and the MemoryFormFactor data type should be a Number instead of other types, otherwise it will cause a warning such as "OCS: Failed to parse string field of type" at startup.
 3.Can the three contents of DataHub, PlatformNVRAM and Generic be changed into three independent tags instead of being merged together? This is more intuitive!

**Comment by mackie100** [comment]
Ok, I'll check in the next few days

**Comment by btwise** [comment]
> 好吧，我会在接下来的几天内检查

OK!

**Comment by btwise** [comment]
> Ok, I'll check in the next few days

Did you fix the problem?

**Comment by mackie100** [comment]
> > Ok, I'll check in the next few days
> 
> Did you fix the problem?

Yes, I will send update tomorrow night....

**Comment by btwise** [comment]
> Yes, I will send update tomorrow night....
Update new translation merges before posting！
Can the OCC default icon be replaced by the OpenCore default color icon?

**Comment by btwise** [comment]
> > > Ok, I'll check in the next few days
> > 
> > 
> > Did you fix the problem?
> 
> Yes, I will send update tomorrow night....

Update new translation merges before posting！
Can the OCC default icon be replaced by the OpenCore default color icon?

**Comment by mackie100** [comment]
I've big server issue, I'll send update tomorrow.........

**Comment by btwise** [comment]
> I've big server issue, I'll send update tomorrow.........

You can also sync your site to Github, your current site, which is slow to access in our country.

**Comment by btwise** [comment]
Can you send a new version to my email? I'll test it.tyq@qq.com
