### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#172]
@mackie100 
`BootstrapShort `options and tips are **_missing_** in `Misc-->Security-->BootProtect`!

**Comment by btwise** [comment]
@mackie100 
update databasedb279854b5d5ff1cb38d80c3dd87c87650a1bdf1

**Comment by mackie100** [comment]
@btwise Feedback and suggestions were moved here https://github.com/mackie100/OCClocalizations/discussions/108
