### ISSUE TITLE
about config templates？

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#194]
@mackie100 
I saw that you have added some configuration template files. Do you want to add template functions for different configurations? Where are these files collected from? The file content is not complete, at least some ACPI patches and some associated configuration should be added!

**Comment by mackie100** [comment]
> @mackie100
> I saw that you have added some configuration template files. Do you want to add template functions for different configurations? Where are these files collected from? The file content is not complete, at least some ACPI patches and some associated configuration should be added!

From Dortania's guide. I've been thinking that user can add manually following the guide. There are many configs, legacy and uefi configurations. My app considers UEFI config.

**Comment by btwise** [comment]
> > @mackie100
> > I saw that you have added some configuration template files. Do you want to add template functions for different configurations? Where are these files collected from? The file content is not complete, at least some ACPI patches and some associated configuration should be added!
> 
> From Dortania's guide. I've been thinking that user can add manually following the guide. There are many configs, legacy and uefi configurations. My app considers UEFI config.

I think it is possible to integrate an automatic generation tool, adopt an intelligent wizard mode, passively improve the configuration file through the user's choice, and download ACPI patch files, public resources, driver files, next files，boot interface and other resources that have been added in the configuration file, and finally generate a complete EFI folder

**Comment by btwise** [comment]
> > @mackie100
> > I saw that you have added some configuration template files. Do you want to add template functions for different configurations? Where are these files collected from? The file content is not complete, at least some ACPI patches and some associated configuration should be added!
> 
> From Dortania's guide. I've been thinking that user can add manually following the guide. There are many configs, legacy and uefi configurations. My app considers UEFI config.

Dortania's Guide is very confident and complete, wouldn't it be great to turn these textual guides into a tools software?
