### ISSUE TITLE
Please fix a problem

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#200]
@mackie100 
In the `Misc-->Boot-->PickerVariant` section, if users select` Other value`, an input box should appear for the user to enter the value of the custom icns set!

**Comment by mackie100** [comment]
Fixed. Thank you.

**Comment by btwise** [comment]
@mackie100 
  2.29.0 version in `Misc-->Boot-->PickerVariant`  Invalid localization character, please fix it

**Comment by mackie100** [comment]
> @mackie100
> 2.29.0 version in `Misc-->Boot-->PickerVariant` Invalid localization character, please fix it

How can i fix that?

**Comment by mackie100** [comment]
@btwise Please translate 51st line in uefiController.strings. Thanks.
