### ISSUE TITLE
EFI Maker is not normal！

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#215]
@mackie100 @bluehomewu 
After switching to Traditional Chinese, EFI Maker cannot select SMBIOS and cannot generate EFI files，Use other language normal!
![image](https://user-images.githubusercontent.com/38809560/110904898-a12c9380-8344-11eb-8811-0b05433e9bfc.png)

**Comment by bluehomewu** [comment]
> @mackie100 @bluehomewu 
> After switching to Traditional Chinese, EFI Maker cannot select SMBIOS and cannot generate EFI files，Use other language normal!
> ![image](https://user-images.githubusercontent.com/38809560/110904898-a12c9380-8344-11eb-8811-0b05433e9bfc.png)
> 

Maybe it is my problem,On this weekend,I will upload translate about latest 2 commit which upload from @mackie100 .
Please wait for me😭.
I'm still High school student this semester.
I only have enough times for work on weekend.

**Comment by bluehomewu** [comment]
@btwise where can I find EFI Maker?

**Comment by btwise** [comment]
> @btwise在哪里可以找到EFI Maker？



> @btwise在哪里可以找到EFI Maker？

在顶部的菜单栏里，标准的cocoa应用程序，顶部都会有菜单栏的

**Comment by mackie100** [comment]
@btwise @bluehomewu Sorry, I did forget to add bundled data
