### ISSUE TITLE
Please update ocs for 0.6.8

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#230]
@mackie100 
Please update ocs for 0.6.8!

**Comment by mackie100** [comment]
> @mackie100
> Please update ocs for 0.6.8!

Thank you for this update.

**Comment by mackie100** [comment]
> @mackie100
> Please update ocs for 0.6.8!

![screen](https://user-images.githubusercontent.com/37126690/114415727-3c1cc580-9bb0-11eb-966d-217b0c193cee.png)
Needs to add GopPassThrough key

**Comment by mackie100** [comment]
> @mackie100
> Please update ocs for 0.6.8!

![screen](https://user-images.githubusercontent.com/37126690/114415727-3c1cc580-9bb0-11eb-966d-217b0c193cee.png)
Needs to add GopPassThrough key

**Comment by btwise** [comment]
Ok

**Comment by btwise** [comment]
> > @mackie100
> > Please update ocs for 0.6.8!
> 
> ![screen](https://user-images.githubusercontent.com/37126690/114415727-3c1cc580-9bb0-11eb-966d-217b0c193cee.png)
> Needs to add GopPassThrough key

GopPassThrough key alreday exist,is count number error!
