### ISSUE TITLE
my git resources!

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#238]
@mackie100 
**OpenCorePkg**:`https://codechina.csdn.net/btwise/OpenCorePkg.git`
                           `https://gitee.com/btwise/OpenCorePkg`
**AUDK**:https://codechina.csdn.net/btwise/audk.git
                  (no gitee)
**OcBinaryData**:`https://codechina.csdn.net/btwise/OcBinaryData.git`
                          `https://gitee.com/btwise/OcBinaryData`
Poll mechanism can be established!

**Comment by mackie100** [comment]
> @mackie100
> **OpenCorePkg**:`https://codechina.csdn.net/btwise/OpenCorePkg.git`
> `https://gitee.com/btwise/OpenCorePkg`
> **AUDK**:https://codechina.csdn.net/btwise/audk.git
> (no gitee)
> **OcBinaryData**:`https://codechina.csdn.net/btwise/OcBinaryData.git`
> `https://gitee.com/btwise/OcBinaryData`
> Poll mechanism can be established!

AUDK url returns 500 error

**Comment by btwise** [comment]
> > @ mackie100 
> > **OpenCorePkg**：`https://codechina.csdn.net/btwise/OpenCorePkg.git`
> > `https://gitee.com/btwise/OpenCorePkg`
> > **AUDK**：[https](https://codechina.csdn.net/btwise/audk.git) 
> > ://codechina.csdn.net/btwise/audk.git（没有gitee

> > @mackie100
> > **OpenCorePkg**:`https://codechina.csdn.net/btwise/OpenCorePkg.git`
> > `https://gitee.com/btwise/OpenCorePkg`
> > **AUDK**:https://codechina.csdn.net/btwise/audk.git
> > (no gitee)
> > **OcBinaryData**:`https://codechina.csdn.net/btwise/OcBinaryData.git`
> > `https://gitee.com/btwise/OcBinaryData`
> > Poll mechanism can be established!
> 
> AUDK url returns 500 error

This is the site's problem, but access to resources should be done using Git, not HTTPS，This is the site's problem, but access to resources should be done using Git, not HTTPS

**Comment by btwise** [comment]
@mackie100 
500 error fixed!

**Comment by mackie100** [comment]
> @mackie100
> 500 error fixed!

Compiler stuck at:
make: *** No rule to make target `Darwin_X64/ValidateNvram.o', needed by `ocvalidate'.  Stop.
make: *** Waiting for unfinished jobs....

**Comment by btwise** [comment]
@mackie100 
send test code to me

**Comment by btwise** [comment]
> > @mackie100
> > 500 error fixed!
> 
> Compiler stuck at:
> make: *** No rule to make target `Darwin_X64/ValidateNvram.o', needed by `ocvalidate'. Stop.
> make: *** Waiting for unfinished jobs....

I use build_oc scripts very ok

**Comment by btwise** [comment]
> > @ mackie100 
> > 500错误已修复！
> 
> 编译器停留在：
> make：***没有使目标`Darwin_X64/ValidateNvram.o', needed by `无效的规则。停止。
> 使：***等待未完成的工作。



> > > @mackie100
> > > 500 error fixed!
> > 
> > 
> > Compiler stuck at:
> > make: *** No rule to make target `Darwin_X64/ValidateNvram.o', needed by `ocvalidate'. Stop.
> > make: *** Waiting for unfinished jobs....
> 
> I use build_oc scripts very ok

This error occurs because validateNvram.c uses validateNVRAM.c capital file name, which has been fixed, and you are trying

**Comment by btwise** [comment]
> > > @ mackie100
> > > 500错误已修复！
> > 
> > 
> > 编译器停留在：
> > make：
> > > > @mackie100
> > > > 500 error fixed!
> > > 
> > > 
> > > Compiler stuck at:
> > > make: *** No rule to make target `Darwin_X64/ValidateNvram.o', needed by `ocvalidate'. Stop.
> > > make: *** Waiting for unfinished jobs....
> > 
> > 
> > I use build_oc scripts is very ok
> 
> This error occurs because validateNvram.c used validateNVRAM.c capital file name, which has been fixed, and you try it again

**Comment by mackie100** [comment]
> > > > @ mackie100
> > > > 500错误已修复！
> > > 
> > > 
> > > 编译器停留在：
> > > make：
> > > > > @mackie100
> > > > > 500 error fixed!
> > > > 
> > > > 
> > > > Compiler stuck at:
> > > > make: *** No rule to make target `Darwin_X64/ValidateNvram.o', needed by `ocvalidate'. Stop.
> > > > make: *** Waiting for unfinished jobs....
> > > 
> > > 
> > > I use build_oc scripts is very ok
> > 
> > 
> > This error occurs because validateNvram.c used validateNVRAM.c capital file name, which has been fixed, and you try it again

Now works good. Thank you

**Comment by btwise** [comment]
@mackie100 
Send builder app to me test
