### ISSUE TITLE
oc builder advice!

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#246]
@mackie100 
![image](https://user-images.githubusercontent.com/38809560/117089598-85fc6400-ad88-11eb-9904-9c1054336563.png)
This should be changed to select the user defined folder instead of the disk partition, after compiling should automatically open the corresponding folder!

**Comment by btwise** [comment]
@mackie100 

When using OCC to build the latest OC development version, there is always a build error, but no detailed error log is given

**Comment by mackie100** [comment]
> @mackie100
> 
> When using OCC to build the latest OC development version, there is always a build error, but no detailed error log is given

I just tested with no build errors occurred.
