### ISSUE TITLE
PickerVariant values are automatically obtained

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#273]
@mackie100 
In the **Misc-> Boot-> pickerVariant** section, its values` Auto` and `Default` are fixed. Can other values be obtained by automatically scanning the subdirectories under `EFI\OC\Resources\Images` to get the contents of optional values?

In addition, due to the version change of OC, the requirements of many themes will often change, so the theme interface cannot work normally. Could you add a theme inspector to check whether the theme file of the corresponding version is missing or wrong? If yes, I will list the specific inspection rules to you in detail!

**Comment by mackie100** [comment]
> @mackie100
> In the **Misc-> Boot-> pickerVariant** section, its values` Auto` and `Default` are fixed. Can other values be obtained by automatically scanning the subdirectories under `EFI\OC\Resources\Images` to get the contents of optional values?
> 
> In addition, due to the version change of OC, the requirements of many themes will often change, so the theme interface cannot work normally. Could you add a theme inspector to check whether the theme file of the corresponding version is missing or wrong? If yes, I will list the specific inspection rules to you in detail!

What are the requirements for a proper theme?

**Comment by btwise** [comment]
> What are the requirements for a proper theme?

**According to the official requirements of OC, a complete topic must meet the following criteria:**
1. _Folder structure_
   EFI
      |---OC
               |---Resources
                            |--------Audio(optional)
                                           Font(required)
                                           Image(required)
                                           Label(required)
2. _File standards_
     Font folder:(required)
                     Font_1x.bin
                     Font_1x.png
                     Font_2x.bin
                     Font_2x.png
     Label folder:(required)
                     Apple.l2x
                     Apple.lbl
                     AppleRecv.l2x
                     AppleRecv.lbl
                     AppleTM.l2x
                     AppleTM.lbl
                     EFIBoot.l2x
                     EFIBoot.lbl
                     Other.l2x
                     Other.lbl
                     ResetNVRAM.l2x
                     ResetNVRAM.lbl
                     SIPDisabled.l2x
                     SIPDisabled.lbl
                     SIPEnabled.l2x
                     SIPEnabled.lbl
                     Shell.l2x
                     Shell.lbl
                     Tool.l2x
                     Tool.lbl
                     Windows.l2x
                     Windows.lbl
      _Image under the two layers of subdirectory icon file:(22 files are required)_
                     AppleRecv.icns
                     AppleTM.icns
                     BtnFocus.icns
                     Cursor.icns
                     Dot.icns
                     Enter.icns
                     ExtAppleRecv.icns
                     ExtAppleTM.icns
                     ExtHardDrive.icns
                     HardDrive.icns
                     Left.icns
                     Lock.icns
                     Password.icns
                     Restart.icns
                     Right.icns
                     Selected.icns
                     Selector.icns
                     SetDefault.icns
                     Shell.icns
                     ShutDown.icns
                     Tool.icns
                     Windows.icns
 _3. Format standard_
      Icon file format must be Mac OS X icon,  "ic07" type
      Other formats are available for the offcial
_4. size standard_
     The selector.icns must be the same size as setDefault.icns. The default value is 80px.

**Comment by mackie100** [comment]
@btwise please translate this string: Add Audio Files
