### ISSUE TITLE
Again, it is recommended to change the way the Tips window is displayed!

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#28]
When clicking the mouse in the main window, the Tips window is always blocked, and you have to constantly select the display Tips window from the main menu. This is a bad experience, it is recommended to increase the display Tips window keyboard shortcuts or set always in the front and can be set Tips window transparency!

**Comment by btwise** [comment]
The Tips window can be set to not appear next time, so that users can control it!
CCG is the same Tips window, modify it!

**Comment by mackie100** [comment]
Let me add three options in preferences pane:
1. Show window at launch;
2. Window transparency or not
3. Keep window front

**Comment by mackie100** [comment]
(https://user-images.githubusercontent.com/37126690/73451285-92b13180-4367-11ea-81b9-a87a49ac5be0.png)

**Comment by mackie100** [comment]
![window transparency](https://user-images.githubusercontent.com/37126690/73451376-c4c29380-4367-11ea-9511-3320157a2096.png)

**Comment by btwise** [comment]
> Let me add three options in preferences pane:
> 
> 1. Show window at launch;
> 2. Window transparency or not
> 3. Keep window front

It looks great, but to be logical, the prompt window can be closed at any time, it can be opened quickly at any time, and transparency is best customizable, because everyone's perspective is different

**Comment by mackie100** [comment]
Added a circle slider that sets alpha value from 0,5 to 0,9 (0,8 default value) 
![shot](https://user-images.githubusercontent.com/37126690/73556655-252d0000-4450-11ea-85f7-169108067a83.png)

**Comment by mackie100** [comment]
added shortcut ^T (control + T) (show tips window when is hidden)

**Comment by btwise** [comment]
very good!
