### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#3]
All of the previous translations I tested in 1.10.2.0 seemed to work fine. I don't know why you made these changes?

**Comment by btwise** [comment]
Iam penguin

**Comment by mackie100** [comment]
> All of the previous translations I tested in 1.10.2.0 seemed to work fine. I don't know why you made these changes?

Because your string files don't respect original order.

**Comment by btwise** [comment]
Then why is the display working? I'm not a developer. I don't know much about this

**Comment by mackie100** [comment]
> Then why is the display working? I'm not a developer. I don't know much about this

Your translations are ok, but the order is not equal like in English string files.
