### ISSUE TITLE
Found a new bug！！

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#33]
In OCC, MISC-> ConsoleBehaviourOs and ConsoleBehaviourUI select the contents of the list. After saving, the contents of these two keys will be lost! Please check the fix!

**Comment by mackie100** [comment]
> In OCC, MISC-> ConsoleBehaviourOs and ConsoleBehaviourUI select the contents of the list. After saving, the contents of these two keys will be lost! Please check the fix!

I'm checking but it works

**Comment by btwise** [comment]
Not ready for the new version?

**Comment by mackie100** [comment]
Not yet. I'm updating platformdata infos...

**Comment by btwise** [comment]
> 还没。我正在更新platformdata信息...

You can refer to the hackintool source code to see if you can add some of its modules, such as generating device property injection content?

**Comment by btwise** [comment]
> > 在OCC中，MISC-> ConsoleBehaviourOs和ConsoleBehaviourUI选择列表的内容。保存后，这两个键的内容将丢失！请检查修复！
> 
> 我正在检查，但是可以

The problem does exist! When the contents selected by Console Behaviour Os and Console Behaviour UI selected ForceGraphics, OCC will delete these two keys when saving, and it is normal to select other contents

**Comment by btwise** [comment]
> > In OCC, MISC-> ConsoleBehaviourOs and ConsoleBehaviourUI select the contents of the list. After saving, the contents of these two keys will be lost! Please check the fix!
> 
> I'm checking but it works

The problem does exist! When the contents selected by Console Behaviour Os and Console Behaviour UI selected ForceGraphics, OCC will delete these two keys when saving, and it is normal to select other contents
