### ISSUE TITLE
Some feature suggestions

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#37]
Can you add a simple HTML tag or markdown tag to the prompt box? This can easily edit some font colors or fonts to prevent URL linking!
Localized language can add the function of automatic online update has avoided the disadvantages of repeated software release！

**Comment by mackie100** [comment]
> Can you add a simple HTML tag or markdown tag to the prompt box? This can easily edit some font colors or fonts to prevent URL linking!
> Localized language can add the function of automatic online update has avoided the disadvantages of repeated software release！

What do you mean "prompt box"?
I don't know a valid online translator or api for free...

**Comment by btwise** [comment]
prompt box means Tips Window!
Not Using the translation API!
I mean that OCC's APP automatically checks the translation resource files on GITHUB every time it starts up, and if there are updates that are automatically downloaded, then we just need to update the local resource files and don't need to redistribute the software

**Comment by mackie100** [comment]
big work to rewrite all objects ids

**Comment by btwise** [comment]
> big work to rewrite all objects ids

Just increase. Does it affect object ID？
