### ISSUE TITLE
fix localizations

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#379]
@mackie100 

“**Keep unknown keys and value**s” and "**Select this option before loading**" in the preferences is not localized

**Comment by mackie100** [comment]
Translation needed

**Comment by mackie100** [comment]
> @mackie100
> 
> “**Keep unknown keys and value**s” and "**Select this option before loading**" in the preferences is not localized

Translation needed

**Comment by btwise** [comment]
> > @mackie100
> > “**Keep unknown keys and value**s” and "**Select this option before loading**" in the preferences is not localized
> 
> Translation needed

I didn't find it in the localization file！

**Comment by mackie100** [comment]
> > > @mackie100
> > > “**Keep unknown keys and value**s” and "**Select this option before loading**" in the preferences is not localized
> > 
> > 
> > Translation needed
> 
> I didn't find it in the localization file！

https://github.com/mackie100/OCClocalizations/blob/5cac27082bcfc4b12e70e8cf314e88c521b5490b/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/Internal/MainMenu.strings#L342

https://github.com/mackie100/OCClocalizations/blob/5cac27082bcfc4b12e70e8cf314e88c521b5490b/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/Internal/MainMenu.strings#L444

**Comment by btwise** [comment]
> 



> > > > @mackie100
> > > > “**Keep unknown keys and value**s” and "**Select this option before loading**" in the preferences is not localized
> > > 
> > > 
> > > Translation needed
> > 
> > 
> > I didn't find it in the localization file！
> 
> https://github.com/mackie100/OCClocalizations/blob/5cac27082bcfc4b12e70e8cf314e88c521b5490b/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/Internal/MainMenu.strings#L342
> 
> https://github.com/mackie100/OCClocalizations/blob/5cac27082bcfc4b12e70e8cf314e88c521b5490b/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/Internal/MainMenu.strings#L444

oh, I was negligent.
