### ISSUE TITLE
I want to ask you to add a utility!

### ISSUE THREAD

**Issue by btwise** [mackie100/OCClocalizations#39]
In the Misc-> Entries section, adding a custom entry is a very useful function, but finding the pci path to add the boot partition is very troublesome. The general practice is to replace the DEBUG version, enable the DEBUG function, and then start it once. Look for log records in the EFI partition, find the PCI path corresponding to the UUID of your partition, and then add it. This is very tedious!
So I hope you can add a scan button in this part of OCC, after clicking, it will scan the UUID and PCI path of all the current partitions, and then the user chooses to copy into the custom entry, I wonder if it is easy for you to complete it?
![image](https://user-images.githubusercontent.com/38809560/74012579-90814f80-49c5-11ea-92eb-a97b9d0d13ba.png)

**Comment by mackie100** [comment]
i can get uuid from a disk. I can't figure out get full pci path

**Comment by btwise** [comment]
This is Uefi boot knowledge, and it's included in the OpenCore  library!
