### ISSUE TITLE
Check untranslated items

### ISSUE THREAD

**Issue by mackie100** [mackie100/OCClocalizations#6]
@btwise There are some items that need translations:

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L8

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L20

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L23

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L35

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L44

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L80

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L83

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L98

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L101

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/acpiController.strings#L110

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/kernelController.strings#L32

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/kernelController.strings#L65

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/kernelController.strings#L107

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/kernelController.strings#L122

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/kernelController.strings#L158

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/kernelController.strings#L164

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L2

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L5

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L14

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L101

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L107

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L119

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L122

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L155

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L158

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L185

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/miscController.strings#L197

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/nvramController.strings#L2

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/nvramController.strings#L5

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/nvramController.strings#L11

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/nvramController.strings#L14

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/nvramController.strings#L20

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/nvramController.strings#L38

https://github.com/mackie100/OCClocalizations/blob/616fca25ba5b686d1bcfae38e288a821fb1d6a68/Chinese%2C%20Simplified%20Localization%20(zh-Hans)/platformInfoController.strings#L5

**Comment by btwise** [comment]
like "mask","oemtableid" words,how do translate?

**Comment by btwise** [comment]
These are ACPI terms that don't have an exact meaning
