### ISSUE TITLE
Please correct new errors below

### ISSUE THREAD

**Issue by mackie100** [mackie100/OCClocalizations#63]
@droofy 

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L6

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L15

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L17

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L27

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L33

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L36

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L39

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L42

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L45

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L48

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L51

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L54

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L63

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L69

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L72

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L75

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L81

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L84

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L87

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L90

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L93

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L96

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L102

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L108

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L111

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L114

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L117

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L120

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/acpiController.strings#L123

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L21

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L24

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L33

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L36

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L42

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L45

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L48

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L51

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L54

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L66

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L69

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L72

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L75

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L78

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L84

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L93

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L102

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L105

https://github.com/mackie100/OCClocalizations/blob/29d220cd2c88a090f9c349e260e7c8d21e36b4f5/French%20localization%20(fr)/Sections/booterController.strings#L108

**Comment by droofy** [comment]
Hello,

I am not used to working with Github, probably by handling error, some files were originally returned untranslated.

Here is an attachment of the work done.

There will still be some translations to correct when they are integrated into the program.

Thank you
